CREATE TABLE [dbo].[ChangeLog]
(
	[Id]			INT					NOT NULL PRIMARY KEY IDENTITY(1,1), 
	[DateTime]		DATETIMEOFFSET		NOT NULL, 
	[UserId]		UNIQUEIDENTIFIER	NOT NULL, 
	[Text]			NVARCHAR(MAX)		NOT NULL
)
