CREATE TABLE [dbo].[User](
	[Id]			UNIQUEIDENTIFIER	NOT NULL,
	[FullName]		NVARCHAR (255)		NOT NULL,
	[Login]			NVARCHAR (55) 		NOT NULL,
	[Hash]			NVARCHAR (255)		NOT NULL,
	[Salt]			NVARCHAR (255)		NOT NULL,
	[IsActive]		BIT					NOT NULL	DEFAULT(1),
	[IsAdmin]		BIT					NOT NULL	DEFAULT(0),
    CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED ([Id] ASC)
);

GO

CREATE UNIQUE NONCLUSTERED INDEX [IX_User] ON [dbo].[User]
(
	[Login] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]


GO